### ISSUE TITLE
Creating processing_manual log failing some times

### ISSUE THREAD

**Issue by bmarcote** [bmarcote/evn_postprocess#3]
For e-EVN experiments, when running for the first time `postprocess`, it breaks with:

```
> create_processing_log.py -o processing_manual.log EC082B
Traceback (most recent call last):
  File "/data0/marcote/scripts/evn_postprocess/app.py", line 182, in <module>
    main()
  File "/data0/marcote/scripts/evn_postprocess/app.py", line 167, in main
    env.shell_command('create_processing_log.py', ['-o', 'processing_manual.log', exp.expname], shell=True)
  File "/data0/marcote/scripts/evn_postprocess/evn_postprocess/environment.py", line 66, in shell_command
    raise ValueError(f"Error code {process.returncode} when running {command} {parameters} in ccs.")
ValueError: Error code 1 when running create_processing_log.py ['-o', 'processing_manual.log', 'EC082B'] in ccs.
```

However, running again it works fine. **Check**.

**Comment by bmarcote** [comment]
By reading my own documentation, `create_processing_log.py` requires the flag `-e eEVNname` when running an e-EVN experiment if the current experiment name is not the name used to call the whole session (`eEVNname`).
Solved!
